spring:
  datasource:
    url: jdbc:h2:~/tacos_h2_2
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    cache: false
server:
  port: 8443
  ssl:
    key-store: file:///home/lorenzo/mykeys.jks
    key-store-password: letmein
    key-password: letmein
logging:
  level:
    root: WARN
    org.springframework.security: WARN
    org.springframework.data: DEBUG
taco:
  orders:
    pageSize: 10